version: 2.1

jobs:
  update_data:
    docker:
      - image: cimg/python:3.6.4
    steps:
      - add_ssh_keys:
          fingerprints:
            - "b2:23:c5:59:24:85:48:01:d7:7d:fc:ca:10:ed:59:a9"
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            - v1-dependencies-
      - run:
          name: Install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}
      - run:
          name: Update data
          no_output_timeout: 60m
          command: |
            . venv/bin/activate
            python mal_synopsis.py --name ati703 --type anime --urlcss https://lebbenszki.github.io/daily/new_anime.css --bearer $bearerToken
            python mal_synopsis.py --name ati703 --type manga --urlcss https://lebbenszki.github.io/daily/new_manga.css --bearer $bearerToken
      - run:
          name: Commit data back to Github
          command: |
            git config user.email "lebbenszki.attila@gmail.com"
            git config user.name "lebbenszki-bot"
            DATE_TODAY=$(date +"%Y-%m-%d")
            git pull origin master
            git commit -am "[skip ci] Updating Data ${DATE_TODAY}" --allow-empty
            git push origin master

workflows:
  daily_data_update:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - update_data

  update_data_on_commit:
    jobs:
      - update_data:
          filters:
            branches:
              only:
                - master
