version: 2.1

jobs:
  update_data:
    docker:
      - image: circleci/python:3.6.4
    steps:
      - add_ssh_keys:
          fingerprints:
            - "60:de:64:e5:3b:0c:55:71:45:d2:b3:1f:b5:12:c8:36"
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            - v1-dependencies-
      - run:
          name: Install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}
      - run:
          name: Update data
          command: |
            . venv/bin/activate
            python mal_synopsis.py ati703 anime https://dl.dropboxusercontent.com/s/u30l2xgi4fg21zs/komolyabb.css
            python mal_synopsis.py ati703 manga https://dl.dropboxusercontent.com/s/rrc8b670cpi5rgx/manga.css
      - run:
          name: Commit data back to Github
          command: |
            git config user.email "ati703@gmail.com"
            git config user.name "lebbenszki"
            DATE_TODAY=$(date +"%Y-%m-%d")
            git pull origin master
            git commit -am "[skip ci] Updating Data ${DATE_TODAY}" --allow-empty
            git push origin master

workflows:
  daily_data_update:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - update_data

  update_data_on_commit:
    jobs:
      - update_data:
          filters:
            branches:
              only:
                - master
